/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CorIcon: typeof import('./components/corIcon/index.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    IEpLocation: typeof import('~icons/ep/location')['default'];
    IEpPlus: typeof import('~icons/ep/plus')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
